from __future__ import annotations

"""Build the source training-period daily profiles used by DTW clustering.

Inputs are generated by the public data-preparation and sample-construction stages.
This module constructs one 48-slot Europe/London profile for each formal source
household, applies the locked per-profile standardisation, identifies the
prototype-estimation subset, and computes the full DTW distance matrix used by
the downstream K-selection stage.

No target-dataset observations, forecasting errors, survey variables, validation
rows, or test rows are used here.
"""

import argparse
import json
import os
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

EXPECTED_HOUSEHOLDS = 3_843
EXPECTED_LOW_SIGNAL_PROFILES = 54
PROFILE_SLOTS = 48
TRAIN_START = pd.Timestamp("2013-01-02 00:00:00")
TRAIN_END = pd.Timestamp("2013-09-13 18:30:00")
EXCLUDED_LOCAL_DATES = {pd.Timestamp("2013-03-31").date()}
LOW_SIGNAL_STD_THRESHOLD_KWH = 0.01
EXPECTED_INDEX_ROWS = {
    1: 66_730_596,
    12: 66_680_560,
    48: 66_530_821,
}
ID_CANDIDATES = ("household_id", "entity_id", "meter_id", "id")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument("--n-jobs", type=int, default=int(os.environ.get("SLURM_CPUS_PER_TASK", "1")))
    parser.add_argument("--preflight-only", action="store_true")
    return parser.parse_args()


def choose_id_column(columns: Iterable[str], source: Path) -> str:
    columns = [str(column) for column in columns]
    for candidate in ID_CANDIDATES:
        if candidate in columns:
            return candidate
    raise AssertionError(f"No household identifier column found in {source}; columns={columns}")


def clean_ids(series: pd.Series, source: Path) -> list[str]:
    if series.isna().any():
        raise AssertionError(f"Null household identifiers found in {source}")
    values = series.astype(str).str.strip()
    if values.eq("").any():
        raise AssertionError(f"Blank household identifiers found in {source}")
    if values.duplicated().any():
        examples = values.loc[values.duplicated()].head(10).tolist()
        raise AssertionError(f"Duplicate household identifiers in {source}; examples={examples}")
    return values.tolist()


def required_paths(root: Path) -> dict[str, Path]:
    base = root / "outputs/tables/sample_construction"
    return {
        "raw_load": root / "data/raw/LCL/csv/data_collection/data_tables/consumption_n.csv",
        "local_clock_map": root / "data/processed/time_aligned/lcl_full_local_clock_map.parquet",
        "scaler_table": base / "lcl_production_scaler_table.csv",
        "index_h1": base / "lcl_production_sample_index_h1.parquet",
        "index_h12": base / "lcl_production_sample_index_h12.parquet",
        "index_h48": base / "lcl_production_sample_index_h48.parquet",
    }


def output_paths(root: Path) -> dict[str, Path]:
    table_dir = root / "outputs/tables/profile_clustering/profile_construction"
    array_dir = root / "outputs/arrays/profile_clustering/profile_construction"
    metadata_dir = root / "outputs/metadata/profile_clustering/profile_construction"
    return {
        "table_dir": table_dir,
        "array_dir": array_dir,
        "metadata_dir": metadata_dir,
        "raw_profiles": table_dir / "source_training_profiles_raw_kwh.csv",
        "z_profiles": table_dir / "source_training_profiles_zscore.csv",
        "low_signal": table_dir / "source_training_profile_variation_audit.csv",
        "slot_audit": table_dir / "source_training_profile_slot_audit.csv",
        "cohort": table_dir / "source_training_profile_cohort.csv",
        "fit_ids": table_dir / "source_prototype_fit_households.csv",
        "dtw": array_dir / "source_prototype_fit_dtw_distance_matrix.npy",
        "status": metadata_dir / "source_training_profile_construction_status.json",
    }


def read_formal_cohort(scaler_path: Path) -> list[str]:
    header = pd.read_csv(scaler_path, nrows=0)
    id_column = choose_id_column(header.columns, scaler_path)
    frame = pd.read_csv(scaler_path, usecols=[id_column], dtype={id_column: str})
    ids = clean_ids(frame[id_column], scaler_path)
    if len(ids) != EXPECTED_HOUSEHOLDS:
        raise AssertionError(
            f"Expected {EXPECTED_HOUSEHOLDS:,} source households in the scaler table; found {len(ids):,}"
        )
    return ids


def scan_index_ids(path: Path, expected_rows: int) -> tuple[set[str], str, int]:
    import pyarrow.parquet as pq

    parquet = pq.ParquetFile(path)
    row_count = int(parquet.metadata.num_rows)
    if row_count != expected_rows:
        raise AssertionError(f"Unexpected sample-index row count in {path}: {row_count:,} != {expected_rows:,}")
    id_column = choose_id_column(parquet.schema.names, path)
    values: set[str] = set()
    for batch in parquet.iter_batches(columns=[id_column], batch_size=1_000_000):
        series = batch.column(0).to_pandas().astype(str).str.strip()
        if series.isna().any() or series.eq("").any():
            raise AssertionError(f"Invalid household identifier encountered in {path}")
        values.update(series.unique().tolist())
    return values, id_column, row_count


def verify_cohort(paths: dict[str, Path]) -> tuple[pd.DataFrame, dict[str, object]]:
    ids = read_formal_cohort(paths["scaler_table"])
    formal_set = set(ids)
    index_info: dict[str, object] = {}
    for lead, key in ((1, "index_h1"), (12, "index_h12"), (48, "index_h48")):
        index_ids, id_column, row_count = scan_index_ids(paths[key], EXPECTED_INDEX_ROWS[lead])
        if index_ids != formal_set:
            missing = sorted(formal_set - index_ids)[:10]
            extra = sorted(index_ids - formal_set)[:10]
            raise AssertionError(f"Source household set mismatch at h={lead}; missing={missing}, extra={extra}")
        index_info[str(lead)] = {
            "path": str(paths[key]),
            "id_column": id_column,
            "rows": row_count,
            "unique_households": len(index_ids),
        }

    raw_header = pd.read_csv(paths["raw_load"], nrows=0).columns.astype(str)
    missing_raw = sorted(formal_set - set(raw_header))
    if missing_raw:
        raise AssertionError(f"Formal source households missing from raw LCL table; examples={missing_raw[:10]}")

    cohort = pd.DataFrame({"household_id": ids, "formal_source_cohort": True})
    provenance = {
        "formal_source_households": len(ids),
        "cohort_source": str(paths["scaler_table"]),
        "index_checks": index_info,
        "raw_header_missing_households": 0,
    }
    return cohort, provenance


def construct_profiles(paths: dict[str, Path], household_ids: list[str]) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    time_map = pd.read_parquet(
        paths["local_clock_map"],
        columns=["raw_row_index", "timestamp_gmt", "local_date", "local_slot"],
    )
    time_map["timestamp_gmt"] = pd.to_datetime(time_map["timestamp_gmt"], errors="raise", utc=True).dt.tz_convert(None)
    time_map["local_date"] = pd.to_datetime(time_map["local_date"], errors="raise").dt.date
    time_map["local_slot"] = pd.to_numeric(time_map["local_slot"], errors="raise").astype(np.int16)
    time_map["raw_row_index"] = pd.to_numeric(time_map["raw_row_index"], errors="raise").astype(np.int64)

    selected = time_map.loc[
        time_map["timestamp_gmt"].between(TRAIN_START, TRAIN_END, inclusive="both")
        & ~time_map["local_date"].isin(EXCLUDED_LOCAL_DATES)
        & time_map["local_slot"].between(1, PROFILE_SLOTS)
    ].sort_values("raw_row_index").copy()
    if selected.empty:
        raise AssertionError("No source training-period rows selected for profile construction")
    if selected["local_date"].isin(EXCLUDED_LOCAL_DATES).any():
        raise AssertionError("The excluded local clock-change date entered profile construction")

    min_row = int(selected["raw_row_index"].min())
    max_row = int(selected["raw_row_index"].max())
    block_length = max_row - min_row + 1
    raw_block = pd.read_csv(
        paths["raw_load"],
        usecols=household_ids,
        skiprows=range(1, min_row + 1),
        nrows=block_length,
        low_memory=False,
    ).loc[:, household_ids]
    if len(raw_block) != block_length:
        raise AssertionError(f"Raw LCL block length mismatch: {len(raw_block):,} != {block_length:,}")

    relative_rows = selected["raw_row_index"].to_numpy(dtype=np.int64) - min_row
    values = raw_block.apply(pd.to_numeric, errors="coerce").to_numpy(dtype=np.float32)[relative_rows]
    slots = selected["local_slot"].to_numpy(dtype=np.int16)
    del raw_block

    profiles = np.empty((EXPECTED_HOUSEHOLDS, PROFILE_SLOTS), dtype=np.float64)
    finite_counts = np.zeros((EXPECTED_HOUSEHOLDS, PROFILE_SLOTS), dtype=np.int32)
    for slot in range(1, PROFILE_SLOTS + 1):
        slot_values = values[slots == slot]
        if not len(slot_values):
            raise AssertionError(f"No source training observations for local slot {slot}")
        finite_counts[:, slot - 1] = np.isfinite(slot_values).sum(axis=0)
        with np.errstate(invalid="ignore"):
            profiles[:, slot - 1] = np.nanmean(slot_values, axis=0)

    if not np.isfinite(profiles).all():
        examples = np.argwhere(~np.isfinite(profiles))[:10].tolist()
        raise AssertionError(f"Non-finite daily-profile cells remain; examples={examples}")

    raw_mean = profiles.mean(axis=1)
    raw_std = profiles.std(axis=1, ddof=0)
    low_signal = raw_std < LOW_SIGNAL_STD_THRESHOLD_KWH
    if int(low_signal.sum()) != EXPECTED_LOW_SIGNAL_PROFILES:
        raise AssertionError(
            f"Expected {EXPECTED_LOW_SIGNAL_PROFILES} low-signal source profiles; found {int(low_signal.sum())}"
        )
    z_profiles = (profiles - raw_mean[:, None]) / np.maximum(raw_std, LOW_SIGNAL_STD_THRESHOLD_KWH)[:, None]
    if not np.isfinite(z_profiles).all():
        raise AssertionError("Non-finite standardised source profiles produced")

    slot_columns = [f"slot_{slot:02d}" for slot in range(1, PROFILE_SLOTS + 1)]
    raw_frame = pd.DataFrame(profiles, columns=slot_columns)
    raw_frame.insert(0, "household_id", household_ids)
    z_frame = pd.DataFrame(z_profiles, columns=slot_columns)
    z_frame.insert(0, "household_id", household_ids)

    variation = pd.DataFrame({
        "household_id": household_ids,
        "raw_profile_mean_kwh": raw_mean,
        "raw_profile_std_kwh_ddof0": raw_std,
        "prototype_fit_eligible": ~low_signal,
        "low_signal_threshold_kwh": LOW_SIGNAL_STD_THRESHOLD_KWH,
        "minimum_finite_observations_per_slot": finite_counts.min(axis=1),
        "maximum_finite_observations_per_slot": finite_counts.max(axis=1),
    })

    slot_audit = selected.groupby("local_slot", as_index=False).agg(
        selected_time_rows=("raw_row_index", "size"),
        first_timestamp_gmt=("timestamp_gmt", "min"),
        last_timestamp_gmt=("timestamp_gmt", "max"),
    )
    slot_audit["profile_period_start"] = TRAIN_START
    slot_audit["profile_period_end"] = TRAIN_END
    slot_audit["excluded_local_dates"] = ";".join(sorted(str(value) for value in EXCLUDED_LOCAL_DATES))
    slot_audit["source_households"] = EXPECTED_HOUSEHOLDS
    slot_audit["validation_rows_used"] = 0
    slot_audit["test_rows_used"] = 0
    slot_audit["target_rows_used"] = 0
    return raw_frame, z_frame, variation, slot_audit


def compute_fit_distance_matrix(z_profiles: pd.DataFrame, variation: pd.DataFrame, n_jobs: int) -> tuple[pd.DataFrame, np.ndarray]:
    from tslearn.metrics import cdist_dtw

    slot_columns = [f"slot_{slot:02d}" for slot in range(1, PROFILE_SLOTS + 1)]
    eligible = variation["prototype_fit_eligible"].to_numpy(dtype=bool)
    fit_ids = z_profiles.loc[eligible, ["household_id"]].reset_index(drop=True)
    if len(fit_ids) != EXPECTED_HOUSEHOLDS - EXPECTED_LOW_SIGNAL_PROFILES:
        raise AssertionError("Unexpected source prototype-estimation subset size")
    x = z_profiles.loc[eligible, slot_columns].to_numpy(dtype=np.float64)[:, :, None]
    matrix = np.asarray(cdist_dtw(x, n_jobs=n_jobs, verbose=0), dtype=np.float32)
    np.fill_diagonal(matrix, 0.0)
    if matrix.shape != (len(fit_ids), len(fit_ids)) or not np.isfinite(matrix).all():
        raise AssertionError("Invalid source DTW distance matrix")
    return fit_ids, matrix


def atomic_csv(path: Path, frame: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    frame.to_csv(temporary, index=False)
    os.replace(temporary, path)


def atomic_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, indent=2, default=str) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def main() -> None:
    args = parse_args()
    root = args.project_root.resolve()
    inputs = required_paths(root)
    outputs = output_paths(root)
    missing = [str(path) for path in inputs.values() if not path.is_file()]
    if missing:
        raise FileNotFoundError("Missing source-profile inputs:\n" + "\n".join(missing))

    cohort, provenance = verify_cohort(inputs)
    if args.preflight_only:
        print("SOURCE TRAINING PROFILE CONSTRUCTION PREFLIGHT: PASS")
        return

    raw_profiles, z_profiles, variation, slot_audit = construct_profiles(inputs, cohort["household_id"].tolist())
    fit_ids, dtw_matrix = compute_fit_distance_matrix(z_profiles, variation, args.n_jobs)

    cohort = cohort.merge(
        variation[["household_id", "prototype_fit_eligible"]],
        on="household_id",
        validate="one_to_one",
    )
    atomic_csv(outputs["raw_profiles"], raw_profiles)
    atomic_csv(outputs["z_profiles"], z_profiles)
    atomic_csv(outputs["low_signal"], variation)
    atomic_csv(outputs["slot_audit"], slot_audit)
    atomic_csv(outputs["cohort"], cohort)
    atomic_csv(outputs["fit_ids"], fit_ids)
    outputs["dtw"].parent.mkdir(parents=True, exist_ok=True)
    temporary_matrix = outputs["dtw"].with_suffix(".npy.tmp")
    with temporary_matrix.open("wb") as handle:
        np.save(handle, dtw_matrix)
    os.replace(temporary_matrix, outputs["dtw"])

    atomic_json(outputs["status"], {
        "status": "COMPLETE_PASS",
        "source_households": EXPECTED_HOUSEHOLDS,
        "prototype_fit_households": len(fit_ids),
        "low_signal_profiles": int((~cohort["prototype_fit_eligible"]).sum()),
        "profile_slots": PROFILE_SLOTS,
        "profile_period_start": TRAIN_START,
        "profile_period_end": TRAIN_END,
        "profile_normalisation_ddof": 0,
        "low_signal_threshold_kwh": LOW_SIGNAL_STD_THRESHOLD_KWH,
        "excluded_local_dates": sorted(str(value) for value in EXCLUDED_LOCAL_DATES),
        "validation_rows_used": 0,
        "test_rows_used": 0,
        "target_rows_used": 0,
        "cohort_provenance": provenance,
        "outputs": {key: str(value) for key, value in outputs.items() if key not in {"table_dir", "array_dir", "metadata_dir"}},
    })
    print("SOURCE TRAINING PROFILE CONSTRUCTION: COMPLETE_PASS")


if __name__ == "__main__":
    main()
