from __future__ import annotations

import ast
import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
issues: list[tuple[str, str]] = []
EXECUTABLE_SUFFIXES = {".py", ".json", ".yaml", ".yml", ".sh"}
PUBLIC_TEXT_SUFFIXES = EXECUTABLE_SUFFIXES | {".md", ".txt", ".csv"}
PRIVATE_TOKENS = ("Code/", "/Users/", "/home/", "/mnt/iusers", "/net/scratch/", "C:\\Users\\", "ChatGPT", "Claude")

# Static validation audits the distributable package source, not runtime material
# supplied or generated by a reproducer. In particular, provider raw files may
# be binary PDFs/XLSX files whose arbitrary bytes can resemble Unicode sentinel
# sequences, and repository-local virtual environments contain third-party code.
# These paths are therefore outside the public-source static audit.
RUNTIME_EXCLUDED_PREFIXES = (
    Path("data/raw"),
    Path("data/processed"),
    Path("outputs"),
    Path(".git"),
    Path("validation/preflight_logs"),
)


def excluded_from_static_audit(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    if rel.name == ".DS_Store":
        return True
    if rel.parts and rel.parts[0].startswith(".venv"):
        return True
    return any(rel == prefix or prefix in rel.parents for prefix in RUNTIME_EXCLUDED_PREFIXES)


def issue(path: Path, message: str) -> None:
    try:
        label = str(path.relative_to(ROOT))
    except ValueError:
        label = str(path)
    issues.append((label, message))


for path in ROOT.rglob("*"):
    if not path.is_file():
        continue
    if excluded_from_static_audit(path):
        continue

    if "__pycache__" in path.parts or path.suffix == ".pyc":
        issue(path, "compiled Python/cache file")

    suffix = path.suffix.lower()
    # The validator itself necessarily contains the sentinel strings it checks.
    is_validator = path.resolve() in {
        Path(__file__).resolve(),
        (ROOT / "validation/validate_public_privacy.py").resolve(),
    }
    if suffix in PUBLIC_TEXT_SUFFIXES and not is_validator:
        text = path.read_text(encoding="utf-8", errors="replace")
        for token in PRIVATE_TOKENS:
            if token in text:
                issue(path, f"private/development residue: {token}")
        if re.search(r"\b(?:Task|TASK)\s*\d+", text):
            issue(path, "internal Task numbering")

        # Reference outputs may be described to the reproducer, but executable
        # code/configuration must never consume them as computational inputs.
        if suffix in EXECUTABLE_SUFFIXES and path.name != "README_reference_only.md":
            if "reference_outputs/" in text or "reference_outputs\\" in text:
                issue(path, "executable/config depends on reference_outputs")

    if suffix == ".py":
        try:
            ast.parse(path.read_text(encoding="utf-8"))
        except Exception as exc:
            issue(path, f"Python syntax: {exc}")
    elif suffix == ".json":
        try:
            json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            issue(path, f"JSON parse: {exc}")
    elif suffix in {".yaml", ".yml"}:
        try:
            yaml.safe_load(path.read_text(encoding="utf-8"))
        except Exception as exc:
            issue(path, f"YAML parse: {exc}")

    raw = path.read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        issue(path, "UTF-8 BOM")
    zero_width = ("\u200b", "\u200c", "\u200d", "\ufeff")
    if any(token.encode("utf-8") in raw for token in zero_width):
        issue(path, "zero-width/BOM Unicode")

required = (
    "README.md",
    "documentation/current_report_scope.md",
    "documentation/current_report_figure_contract.md",
    "workflows/README_workflows.md",
    "workflows/prepare_raw_inputs.sh",
    "data_access/README_data_access.md",
    "documentation/privacy_and_publication_contract.md",
    "configs/forecasting_h1.yaml",
    "configs/forecasting_h12.yaml",
    "configs/forecasting_h48.yaml",
)
for relative in required:
    path = ROOT / relative
    if not path.is_file():
        issue(path, "required public file missing")


# Runtime metadata contract. This check is intentionally static so a mismatch
# between the public runtime configuration and the Stage 3 consumer is caught
# during preflight, before raw-data processing reaches sample construction.
CANONICAL_RUNTIME_ROLE = "reproduction_runtime_parameters"
runtime_config_path = ROOT / "configs/forecasting_runtime.yaml"
sample_construction_path = (
    ROOT
    / "code"
    / "03_sample_construction"
    / "sample_construction_production_indexes_scalers.py"
)

if runtime_config_path.is_file():
    try:
        runtime_config = yaml.safe_load(runtime_config_path.read_text(encoding="utf-8"))
        runtime_role = (runtime_config or {}).get("runtime_projection", {}).get("role")
        if runtime_role != CANONICAL_RUNTIME_ROLE:
            issue(
                runtime_config_path,
                "runtime_projection.role does not match the public runtime metadata contract",
            )
    except Exception as exc:
        issue(runtime_config_path, f"runtime metadata contract check: {exc}")

if sample_construction_path.is_file():
    try:
        sample_tree = ast.parse(sample_construction_path.read_text(encoding="utf-8"))
        code_runtime_role = None
        for node in sample_tree.body:
            if not isinstance(node, ast.Assign):
                continue
            if not any(isinstance(t, ast.Name) and t.id == "EXPECTED_RUNTIME_ROLE" for t in node.targets):
                continue
            if isinstance(node.value, ast.Constant):
                code_runtime_role = node.value.value
            break
        if code_runtime_role != CANONICAL_RUNTIME_ROLE:
            issue(
                sample_construction_path,
                "EXPECTED_RUNTIME_ROLE does not match the public runtime metadata contract",
            )
    except Exception as exc:
        issue(sample_construction_path, f"runtime metadata consumer check: {exc}")


# Report-figure producer contract. These checks guard the submitted visual
# information contract (titles, diagnostic definition and key panel structure)
# against accidental simplification in later packaging edits.
FIGURE_SOURCE_CONTRACT = {
    Path("code/01_data_preparation/eligibility/build_lcl_eligibility.py"): [
        "learnable_training_windows_h1",
        "expected_low = [2, 4, 27, 29, 41]",
        "!= 661",
        "Learnable training windows across LCL source households",
    ],
    Path("code/02_eda_and_data_diagnostics/generate_reported_eda.py"): [
        "Average daily load profile: LCL source vs CER target (full modelling periods)",
        "(a) Distribution of household/meter mean load",
        "(b) Spread across households/meters",
    ],
    Path("code/02_eda_and_data_diagnostics/generate_forecast_lead_diagnostic.py"): [
        "Forecast lead analysis",
        "(a) Load dependence across forecast leads",
        "(b) Naive forecast error across forecast leads",
    ],
    Path("code/09_report_output_generation/group_heterogeneity_group_heterogeneity_figures.py"): [
        "Relative MAE gain of Direct Transfer over Scratch Limited by profile group",
        "Box = IQR",
        "No gain",
    ],
    Path("code/09_report_output_generation/figure_4_2_source_relevance.py"): [
        "Source similarity versus transfer gain (h = 12)",
        "Local source support versus transfer gain (h = 12)",
        "Overall household quartile median",
    ],
    Path("code/09_report_output_generation/figure_3_1_design_schematic.py"): [
        "Same global CNN-LSTM architecture",
        "Common target test period",
    ],
}
for relative, tokens in FIGURE_SOURCE_CONTRACT.items():
    path = ROOT / relative
    if not path.is_file():
        issue(path, "required figure producer missing")
        continue
    text = path.read_text(encoding="utf-8")
    for token in tokens:
        if token not in text:
            issue(path, f"submitted figure contract token missing: {token}")

# Datetime continuity checks must normalise to nanoseconds explicitly. pandas 3
# may preserve a different internal datetime unit, so direct .asi8 comparison
# against Timedelta.value is not a portable invariant.
if sample_construction_path.is_file():
    sample_text = sample_construction_path.read_text(encoding="utf-8")
    if "LCL_GRID.asi8" in sample_text or "CER_GRID.asi8" in sample_text:
        issue(sample_construction_path, "non-portable pandas datetime-unit comparison uses .asi8")

scope_path = ROOT / "documentation/current_report_scope.md"
if scope_path.is_file() and "Appendices A–N" in scope_path.read_text(encoding="utf-8"):
    issue(scope_path, "stale A–N scope")

if issues:
    print("STATIC VALIDATION: FAIL")
    for path, message in issues:
        print(f"- {path}: {message}")
    raise SystemExit(1)
print("STATIC VALIDATION: PASS")
